language: node_js
sudo: required
services:
  - docker
cache: yarn
notifications:
  email: false
node_js:
  - '12'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install:
  - yarn
script:
  - yarn lerna run build:prod
  - yarn lerna run test
  - yarn lerna run lint
